app:
  worker:
    interval: 1h
  ignored:
    deployment:
      namespaceName1:
        - deploymentName1
        - deploymentName2
    statefulset:
      namespaceName2:
        - statefulsetName1
    daemonset:
      namespaceName1:
        - daemonsetName1
