app:
  worker:
    interval: 1h
excluding:
  namespaces: namespaceName1,namespaceName2
  deployment:
    namespaceName3:
      deploymentName1: true
      deploymentName2: true
  statefulset:
    namespaceName4:
      statefulsetName1: true
  daemonset:
    namespaceName3:
      daemonsetName1: true
monitors:
  datadog:
    host: localhost:8125
    prefix: resources-check
